name: kitmedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  get: ^4.7.2
  get_storage: ^2.1.1
  
  # Video & Media
  better_player_plus: ^1.1.2
  video_thumbnail: ^0.5.6
  flutter_cache_manager: ^3.4.1
  volume_controller: ^3.4.0
  screen_brightness: ^2.1.7
  wakelock_plus: ^1.4.0
  
  # File & Storage
  external_path: ^2.2.0
  mime: ^2.0.0
  path: ^1.9.1
  
  # UI & Design
  material_symbols_icons: ^4.2874.0
  dynamic_color: ^1.8.1
  expressive_loading_indicator: ^0.0.1
  material_new_shapes: ^1.0.0
  
  # Utility & Enhancement
  device_info_plus: ^12.2.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  connectivity_plus: ^7.0.0

  # Media Processing
  image: ^4.5.4

  # Networking & Downloads
  dio: ^5.9.0
  dio_cache_interceptor: ^4.0.5
  
  
  # Internationalization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
